title: AlexOnTheGrind
description: > # this means to ignore newlines until "baseurl:"
  Always on the Tech Hustle. Full Stack Developer, Budding Entrepreneur, 
  Socialized Sci-Fi geek, Go Giants!
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: AlexOnTheGrind #if your site has a twitter account, enter it here

# Author Settings
author: Alex Maldonado # add your name
author-img: profile-standard.png # add your photo
about-author: > # add description
  Always on the Tech Hustle. Full Stack Developer, Budding Entrepreneur, 
  Socialized Sci-Fi geek, Go Giants!
twitter: AlexOnTheGrind # add your Twitter handle
# facebook: # add your Facebook handle
github: oocoder # add your Github handle
linkedin: # add your Linkedin handle
email: calidadis@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-72908902-4 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
